In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('titanic.csv')

In [3]:
df.head()

  Cabin            Ticket number  Survived
0   NaN         A/5 21171      5         0
1   C85          PC 17599      3         1
2   NaN  STON/O2. 3101282      6         1
3  C123            113803      3         1
4   NaN            373450      A         0

In [4]:
df['number'].unique()

array(['5', '3', '6', 'A', '2', '1', '4'], dtype=object)

In [6]:
df['number_numerical']=pd.to_numeric(df['number'],errors='coerce',downcast='integer')

In [7]:
df.head()

  Cabin            Ticket number  Survived  number_numerical
0   NaN         A/5 21171      5         0               5.0
1   C85          PC 17599      3         1               3.0
2   NaN  STON/O2. 3101282      6         1               6.0
3  C123            113803      3         1               3.0
4   NaN            373450      A         0               NaN

In [8]:
df['number_categorical']=np.where(df['number_numerical'].isnull(),df['number'],np.nan)

In [9]:
df.head()

,Cabin,Ticket,number,Survived,number_numerical,number_categorical
0,NaN,A/5 21171,5,0,5.0,NaN
1,C85,PC 17599,3,1,3.0,NaN
2,NaN,STON/O2. 3101282,6,1,6.0,NaN
3,C123,113803,3,1,3.0,NaN
4,NaN,373450,A,0,NaN,A

In [13]:
df['cabin_num']=df['Cabin'].str.extract('(\d+)')
df['cabin_num']=df['Cabin'].str[0]
df.head()

,Cabin,Ticket,number,Survived,number_numerical,number_categorical,cabin_num
0,NaN,A/5 21171,5,0,5.0,NaN,NaN
1,C85,PC 17599,3,1,3.0,NaN,C
2,NaN,STON/O2. 3101282,6,1,6.0,NaN,NaN
3,C123,113803,3,1,3.0,NaN,C
4,NaN,373450,A,0,NaN,A,NaN