In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('wine_data (1).csv',header=None,usecols=[0,1,2])

In [3]:
df.columns=['class label','Alcohal','malc acid']

In [4]:
df

     class label  Alcohal  malc acid
0              1    14.23       1.71
1              1    13.20       1.78
2              1    13.16       2.36
3              1    14.37       1.95
4              1    13.24       2.59
..           ...      ...        ...
173            3    13.71       5.65
174            3    13.40       3.91
175            3    13.27       4.28
176            3    13.17       2.59
177            3    14.13       4.10

[178 rows x 3 columns]

In [5]:
x=df[['Alcohal','malc acid']]
y=df['class label']

In [6]:
x

     Alcohal  malc acid
0      14.23       1.71
1      13.20       1.78
2      13.16       2.36
3      14.37       1.95
4      13.24       2.59
..       ...        ...
173    13.71       5.65
174    13.40       3.91
175    13.27       4.28
176    13.17       2.59
177    14.13       4.10

[178 rows x 2 columns]

In [7]:
y

0      1
1      1
2      1
3      1
4      1
      ..
173    3
174    3
175    3
176    3
177    3
Name: class label, Length: 178, dtype: int64

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [10]:
from sklearn.preprocessing import MinMaxScaler
Scaler=MinMaxScaler()

In [11]:
Scaler.fit(x_train)

MinMaxScaler()

In [12]:
x_train_scaled=Scaler.transform(x_train)
x_test_scaled=Scaler.transform(x_test)

In [13]:
x_train_scaled=pd.DataFrame(x_train_scaled,columns=x_train.columns)
x_test_scaled=pd.DataFrame(x_test_scaled,columns=x_test.columns)

In [14]:
x_train_scaled

      Alcohal  malc acid
0    0.213158   0.029644
1    0.797368   0.175889
2    0.113158   0.592885
3    0.000000   0.152174
4    0.165789   0.225296
..        ...        ...
137  0.813158   0.146245
138  0.100000   0.000000
139  0.718421   0.156126
140  0.431579   0.047431
141  0.110526   0.328063

[142 rows x 2 columns]

In [16]:
x_test_scaled.shape

(36, 2)

In [17]:
x_train.describe()

          Alcohal   malc acid
count  142.000000  142.000000
mean    12.972113    2.301901
std      0.816190    1.097915
min     11.030000    0.740000
25%     12.332500    1.575000
50%     13.040000    1.830000
75%     13.662500    3.082500
max     14.830000    5.800000

In [18]:
x_test_scaled.describe()

         Alcohal  malc acid
count  36.000000  36.000000
mean    0.548173   0.342336
std     0.209368   0.236452
min     0.139474   0.039526
25%     0.403289   0.183300
50%     0.560526   0.228261
75%     0.706579   0.473320
max     0.884211   0.970356